services:
  app:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./docs:/usr/share/nginx/html

  resizer:
    build: .
    volumes:
      - .:/app
    entrypoint: /app/entrypoint_resize.sh
